import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'id' | 'en' | 'zh' | 'ja';

export const languages: Record<Language, { name: string; nativeName: string; flag: string }> = {
  id: { name: 'Indonesian', nativeName: 'Bahasa Indonesia', flag: '🇮🇩' },
  en: { name: 'English', nativeName: 'English', flag: '🇺🇸' },
  zh: { name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  ja: { name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
};

// Translation keys organized by category
export const translations: Record<Language, Record<string, string>> = {
  id: {
    // Auth
    'auth.welcome': 'Selamat datang',
    'auth.welcomeBack': 'Selamat datang kembali',
    'auth.signInContinue': 'Masuk untuk melanjutkan perjalanan desainmu',
    'auth.createAccount': 'Buat akun baru',
    'auth.startFeedback': 'Mulai dapatkan feedback untuk desainmu',
    'auth.email': 'Email',
    'auth.password': 'Kata sandi',
    'auth.confirmPassword': 'Konfirmasi kata sandi',
    'auth.name': 'Nama',
    'auth.signIn': 'Masuk',
    'auth.signUp': 'Daftar',
    'auth.signUpFree': 'Daftar gratis',
    'auth.noAccount': 'Belum punya akun?',
    'auth.hasAccount': 'Sudah punya akun?',
    'auth.emailPlaceholder': 'hello@contoh.com',
    'auth.namePlaceholder': 'Nama lengkapmu',
    'auth.passwordPlaceholder': '••••••••',
    'auth.selectLanguage': 'Pilih Bahasa',
    
    // Common
    'common.loading': 'Memuat...',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.create': 'Buat',
    'common.search': 'Cari',
    'common.filter': 'Filter',
    'common.all': 'Semua',
    'common.back': 'Kembali',
    'common.next': 'Selanjutnya',
    'common.submit': 'Kirim',
    'common.viewAll': 'Lihat Semua',
    'common.explore': 'Jelajahi',
    'common.getStarted': 'Mulai Sekarang',
    'common.optional': 'opsional',
    
    // Hero/Landing
    'hero.tagline': 'Swipe ideas. Discover talent.',
    'hero.poweredBy': 'Powered by AI.',
    'hero.description': 'Komunitas desainer terbesar untuk berbagi karya dan mendapat feedback berkualitas.',
    'hero.explorePortfolio': 'Jelajahi portofolio desain terbaik dunia',
    'hero.exploreDesc': 'Jutaan desainer dan agensi menampilkan karya portofolio mereka di SwipeLab — rumah bagi desainer dan kreatif profesional terbaik dunia.',
    'hero.shareWork': 'Siap berbagi karyamu?',
    'hero.shareWorkDesc': 'Bergabung dengan ribuan desainer yang mendapat feedback nyata setiap hari.',
    'hero.createFreeAccount': 'Buat Akun Gratis',
    
    // Services
    'services.title': 'Jasa Desainer',
    'services.description': 'Temukan jasa desain profesional dari talenta terbaik',
    'services.createNew': 'Buat Jasa Baru',
    'services.myServices': 'Jasa Saya',
    'services.basicPlan': 'Basic',
    'services.standardPlan': 'Standard',
    'services.premiumPlan': 'Premium',
    'services.days': 'hari',
    'services.revisions': 'revisi',
    'services.orderNow': 'Pesan Sekarang',
    'services.noServices': 'Belum ada jasa tersedia',
    'services.addService': 'Tambah Jasa',
    'services.serviceTitle': 'Judul Jasa',
    'services.serviceDescription': 'Deskripsi Jasa',
    'services.category': 'Kategori',
    'services.price': 'Harga',
    'services.deliveryTime': 'Waktu Pengerjaan',
    'services.faq': 'FAQ',
    'services.portfolio': 'Portfolio',
    'services.testimonials': 'Testimonial',
    'services.basicInfo': 'Informasi Dasar',
    'services.createDesc': 'Buat jasa desain dan mulai dapatkan klien',
    'services.pricingPlans': 'Paket Harga',
    'services.addImage': 'Tambah Gambar',
    'services.question': 'Pertanyaan',
    'services.answer': 'Jawaban',
    
    // Categories
    'category.ui_ux_design': 'UI/UX Design',
    'category.graphic_design': 'Graphic Design',
    'category.illustration': 'Ilustrasi',
    'category.branding': 'Branding',
    'category.web_design': 'Web Design',
    'category.mobile_design': 'Mobile Design',
    'category.motion_graphics': 'Motion Graphics',
    'category.other': 'Lainnya',
    
    // Navigation
    'nav.feed': 'Feed',
    'nav.explore': 'Jelajahi',
    'nav.designers': 'Designer',
    'nav.services': 'Jasa',
    'nav.upload': 'Unggah',
    'nav.dashboard': 'Dashboard',
    'nav.messages': 'Pesan',
    'nav.bookmarks': 'Bookmark',
    'nav.profile': 'Profil',
    'nav.editProfile': 'Edit Profil',
    'nav.myProfile': 'Profil Saya',
    'nav.savedDesigns': 'Desain Tersimpan',
    'nav.logout': 'Keluar',
    'nav.login': 'Masuk',
    'nav.aiAssistant': 'AI Asisten',
    
    // Dashboard
    'dashboard.tagline': 'Swipe ideas. Discover talent.',
    'dashboard.desc': 'Kelola desain Anda, lihat feedback dari komunitas, dan dapatkan insight AI.',
    'dashboard.totalDesigns': 'Total Desain',
    'dashboard.likesReceived': 'Like Diterima',
    'dashboard.designsSwiped': 'Desain Di-swipe',
    'dashboard.myDesigns': 'Desain Saya',
    'dashboard.communityFeedback': 'Feedback Komunitas',
    'dashboard.aiFeedback': 'Feedback AI',
    'dashboard.noDesigns': 'Belum ada desain',
    'dashboard.uploadFirst': 'Unggah desain pertamamu untuk memulai',
    'dashboard.noAiFeedback': 'Belum ada feedback AI',
    'dashboard.requestAi': 'Minta analisis AI pada desainmu untuk mendapat insight',
    
    // Upload
    'upload.title': 'Unggah Desain',
    'upload.shareWork': 'Bagikan karyamu',
    'upload.desc': 'Bagikan kreativitasmu dan dapatkan feedback dari komunitas',
    'upload.designImage': 'Gambar Desain',
    'upload.clickUpload': 'Klik untuk unggah',
    'upload.maxSize': 'PNG, JPG atau WebP (maks 5MB)',
    'upload.titleLabel': 'Judul',
    'upload.titlePlaceholder': 'Beri judul menarik untuk desainmu',
    'upload.categoryLabel': 'Kategori',
    'upload.selectCategory': 'Pilih kategori',
    'upload.descLabel': 'Deskripsi',
    'upload.descPlaceholder': 'Ceritakan tentang desainmu...',
    'upload.submit': 'Unggah Desain',
    
    // Designers
    'designers.title': 'Temukan Designer',
    'designers.desc': 'Temukan desainer berbakat yang siap bekerja sama',
    'designers.searchPlaceholder': 'Cari berdasarkan nama, skill, atau lokasi...',
    'designers.availableForHire': 'Tersedia untuk Hire',
    'designers.mostFollowers': 'Followers Terbanyak',
    'designers.mostDesigns': 'Desain Terbanyak',
    'designers.noFound': 'Tidak ada desainer ditemukan',
    'designers.adjustFilters': 'Coba sesuaikan pencarian atau filter',
    'designers.followers': 'pengikut',
    'designers.designs': 'desain',
    
    // Profile
    'profile.yourProfile': 'Profil Kamu',
    'profile.showCommunity': 'Tampilkan dirimu ke komunitas SwipeLab',
    'profile.photo': 'Foto Profil',
    'profile.photoDesc': 'Klik kamera untuk unggah foto baru',
    'profile.displayName': 'Nama Tampilan',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Ceritakan tentang dirimu ke komunitas...',
    'profile.availableForHire': 'Tersedia untuk Hire',
    'profile.availableDesc': 'Beri tahu orang lain bahwa kamu siap bekerja',
    'profile.location': 'Lokasi',
    'profile.hourlyRate': 'Tarif Per Jam',
    'profile.skills': 'Keahlian',
    'profile.addSkill': 'Tambah keahlian (mis: Figma, UI Design)',
    'profile.saveChanges': 'Simpan Perubahan',
    
    // Feed
    'feed.guestViewing': 'Kamu sedang melihat sebagai tamu',
    'feed.guestSwipes': 'Sisa {count} swipe gratis. Login untuk swipe tanpa batas!',
    'feed.limitReached': 'Kamu sudah mencapai batas swipe. Login untuk melanjutkan!',
    'feed.designsLeft': '{count} desain tersisa untuk dijelajahi',
    'feed.youLikeDesigns': 'Kamu suka design-design ini!',
    'feed.swipedLimit': 'Kamu sudah swipe {count} design. Untuk melanjutkan, silakan login atau buat akun gratis.',
    'feed.unlimitedSwipes': 'Swipe tanpa batas & simpan favoritmu!',
    'feed.maybeLater': 'Nanti saja',
    'feed.registerFree': 'Daftar Gratis',
  },
  en: {
    // Auth
    'auth.welcome': 'Welcome',
    'auth.welcomeBack': 'Welcome back',
    'auth.signInContinue': 'Sign in to continue your design journey',
    'auth.createAccount': 'Create your account',
    'auth.startFeedback': 'Start getting feedback on your designs',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.name': 'Name',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.signUpFree': 'Sign up free',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.emailPlaceholder': 'hello@example.com',
    'auth.namePlaceholder': 'Your full name',
    'auth.passwordPlaceholder': '••••••••',
    'auth.selectLanguage': 'Select Language',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.all': 'All',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.viewAll': 'View All',
    'common.explore': 'Explore',
    'common.getStarted': 'Get Started',
    'common.optional': 'optional',
    
    // Hero/Landing
    'hero.tagline': 'Swipe ideas. Discover talent.',
    'hero.poweredBy': 'Powered by AI.',
    'hero.description': 'The largest designer community to share work and get quality feedback.',
    'hero.explorePortfolio': 'Explore the world\'s leading design portfolio',
    'hero.exploreDesc': 'Millions of designers and agencies showcase their portfolio work on SwipeLab — the home to the world\'s best design and creative professionals.',
    'hero.shareWork': 'Ready to share your work?',
    'hero.shareWorkDesc': 'Join thousands of designers getting real feedback every day.',
    'hero.createFreeAccount': 'Create Free Account',
    
    // Services
    'services.title': 'Designer Services',
    'services.description': 'Find professional design services from top talent',
    'services.createNew': 'Create New Service',
    'services.myServices': 'My Services',
    'services.basicPlan': 'Basic',
    'services.standardPlan': 'Standard',
    'services.premiumPlan': 'Premium',
    'services.days': 'days',
    'services.revisions': 'revisions',
    'services.orderNow': 'Order Now',
    'services.noServices': 'No services available yet',
    'services.addService': 'Add Service',
    'services.serviceTitle': 'Service Title',
    'services.serviceDescription': 'Service Description',
    'services.category': 'Category',
    'services.price': 'Price',
    'services.deliveryTime': 'Delivery Time',
    'services.faq': 'FAQ',
    'services.portfolio': 'Portfolio',
    'services.testimonials': 'Testimonials',
    'services.basicInfo': 'Basic Information',
    'services.createDesc': 'Create a design service and start getting clients',
    'services.pricingPlans': 'Pricing Plans',
    'services.addImage': 'Add Image',
    'services.question': 'Question',
    'services.answer': 'Answer',
    
    // Categories
    'category.ui_ux_design': 'UI/UX Design',
    'category.graphic_design': 'Graphic Design',
    'category.illustration': 'Illustration',
    'category.branding': 'Branding',
    'category.web_design': 'Web Design',
    'category.mobile_design': 'Mobile Design',
    'category.motion_graphics': 'Motion Graphics',
    'category.other': 'Other',
    
    // Navigation
    'nav.feed': 'Feed',
    'nav.explore': 'Explore',
    'nav.designers': 'Designers',
    'nav.services': 'Services',
    'nav.upload': 'Upload',
    'nav.dashboard': 'Dashboard',
    'nav.messages': 'Messages',
    'nav.bookmarks': 'Bookmarks',
    'nav.profile': 'Profile',
    'nav.editProfile': 'Edit Profile',
    'nav.myProfile': 'My Profile',
    'nav.savedDesigns': 'Saved Designs',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'nav.aiAssistant': 'AI Assistant',
    
    // Dashboard
    'dashboard.tagline': 'Swipe ideas. Discover talent.',
    'dashboard.desc': 'Manage your designs, view community feedback, and get AI insights.',
    'dashboard.totalDesigns': 'Total Designs',
    'dashboard.likesReceived': 'Likes Received',
    'dashboard.designsSwiped': 'Designs Swiped',
    'dashboard.myDesigns': 'My Designs',
    'dashboard.communityFeedback': 'Community Feedback',
    'dashboard.aiFeedback': 'AI Feedback',
    'dashboard.noDesigns': 'No designs yet',
    'dashboard.uploadFirst': 'Upload your first design to get started',
    'dashboard.noAiFeedback': 'No AI feedback yet',
    'dashboard.requestAi': 'Request AI analysis on your designs to get insights',
    
    // Upload
    'upload.title': 'Upload a Design',
    'upload.shareWork': 'Share your work',
    'upload.desc': 'Share your creativity and get feedback from the community',
    'upload.designImage': 'Design Image',
    'upload.clickUpload': 'Click to upload',
    'upload.maxSize': 'PNG, JPG or WebP (max 5MB)',
    'upload.titleLabel': 'Title',
    'upload.titlePlaceholder': 'Give your design a catchy title',
    'upload.categoryLabel': 'Category',
    'upload.selectCategory': 'Select a category',
    'upload.descLabel': 'Description',
    'upload.descPlaceholder': 'Tell us about your design...',
    'upload.submit': 'Upload Design',
    
    // Designers
    'designers.title': 'Find Designers',
    'designers.desc': 'Discover talented designers available for hire and collaboration',
    'designers.searchPlaceholder': 'Search by name, skill, or location...',
    'designers.availableForHire': 'Available for Hire',
    'designers.mostFollowers': 'Most Followers',
    'designers.mostDesigns': 'Most Designs',
    'designers.noFound': 'No designers found',
    'designers.adjustFilters': 'Try adjusting your search or filters',
    'designers.followers': 'followers',
    'designers.designs': 'designs',
    
    // Profile
    'profile.yourProfile': 'Your Profile',
    'profile.showCommunity': 'Show yourself to the SwipeLab community',
    'profile.photo': 'Profile Photo',
    'profile.photoDesc': 'Click the camera to upload a new photo',
    'profile.displayName': 'Display Name',
    'profile.bio': 'Bio',
    'profile.bioPlaceholder': 'Tell the community about yourself...',
    'profile.availableForHire': 'Available for Hire',
    'profile.availableDesc': 'Let others know you\'re open to work',
    'profile.location': 'Location',
    'profile.hourlyRate': 'Hourly Rate',
    'profile.skills': 'Skills',
    'profile.addSkill': 'Add a skill (e.g., Figma, UI Design)',
    'profile.saveChanges': 'Save Changes',
    
    // Feed
    'feed.guestViewing': 'You\'re viewing as a guest',
    'feed.guestSwipes': '{count} free swipes left. Login for unlimited swipes!',
    'feed.limitReached': 'You\'ve reached the swipe limit. Login to continue!',
    'feed.designsLeft': '{count} design(s) left to explore',
    'feed.youLikeDesigns': 'You like these designs!',
    'feed.swipedLimit': 'You\'ve swiped {count} designs. To continue, please login or create a free account.',
    'feed.unlimitedSwipes': 'Unlimited swipes & save your favorites!',
    'feed.maybeLater': 'Maybe later',
    'feed.registerFree': 'Register Free',
  },
  zh: {
    // Auth
    'auth.welcome': '欢迎',
    'auth.welcomeBack': '欢迎回来',
    'auth.signInContinue': '登录以继续您的设计之旅',
    'auth.createAccount': '创建账户',
    'auth.startFeedback': '开始获取您设计的反馈',
    'auth.email': '邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.name': '姓名',
    'auth.signIn': '登录',
    'auth.signUp': '注册',
    'auth.signUpFree': '免费注册',
    'auth.noAccount': '还没有账户？',
    'auth.hasAccount': '已有账户？',
    'auth.emailPlaceholder': 'hello@example.com',
    'auth.namePlaceholder': '您的全名',
    'auth.passwordPlaceholder': '••••••••',
    'auth.selectLanguage': '选择语言',
    
    // Common
    'common.loading': '加载中...',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.create': '创建',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.all': '全部',
    'common.back': '返回',
    'common.next': '下一步',
    'common.submit': '提交',
    'common.viewAll': '查看全部',
    'common.explore': '探索',
    'common.getStarted': '开始使用',
    'common.optional': '可选',
    
    // Hero/Landing
    'hero.tagline': '滑动创意。发现人才。',
    'hero.poweredBy': '由AI驱动。',
    'hero.description': '最大的设计师社区，分享作品并获得优质反馈。',
    'hero.explorePortfolio': '探索世界顶级设计作品集',
    'hero.exploreDesc': '数百万设计师和机构在SwipeLab展示他们的作品集——这里是世界上最优秀的设计和创意专业人士的家园。',
    'hero.shareWork': '准备分享您的作品了吗？',
    'hero.shareWorkDesc': '加入每天获得真实反馈的数千名设计师。',
    'hero.createFreeAccount': '创建免费账户',
    
    // Services
    'services.title': '设计师服务',
    'services.description': '寻找顶尖人才的专业设计服务',
    'services.createNew': '创建新服务',
    'services.myServices': '我的服务',
    'services.basicPlan': '基础版',
    'services.standardPlan': '标准版',
    'services.premiumPlan': '高级版',
    'services.days': '天',
    'services.revisions': '次修改',
    'services.orderNow': '立即订购',
    'services.noServices': '暂无可用服务',
    'services.addService': '添加服务',
    'services.serviceTitle': '服务标题',
    'services.serviceDescription': '服务描述',
    'services.category': '类别',
    'services.price': '价格',
    'services.deliveryTime': '交付时间',
    'services.faq': '常见问题',
    'services.portfolio': '作品集',
    'services.testimonials': '评价',
    'services.basicInfo': '基本信息',
    'services.createDesc': '创建设计服务并开始获取客户',
    'services.pricingPlans': '定价方案',
    'services.addImage': '添加图片',
    'services.question': '问题',
    'services.answer': '答案',
    
    // Categories
    'category.ui_ux_design': 'UI/UX 设计',
    'category.graphic_design': '平面设计',
    'category.illustration': '插画',
    'category.branding': '品牌设计',
    'category.web_design': '网页设计',
    'category.mobile_design': '移动端设计',
    'category.motion_graphics': '动态图形',
    'category.other': '其他',
    
    // Navigation
    'nav.feed': '动态',
    'nav.explore': '探索',
    'nav.designers': '设计师',
    'nav.services': '服务',
    'nav.upload': '上传',
    'nav.dashboard': '仪表板',
    'nav.messages': '消息',
    'nav.bookmarks': '收藏',
    'nav.profile': '个人资料',
    'nav.editProfile': '编辑资料',
    'nav.myProfile': '我的资料',
    'nav.savedDesigns': '已保存设计',
    'nav.logout': '退出',
    'nav.login': '登录',
    'nav.aiAssistant': 'AI助手',
    
    // Dashboard
    'dashboard.tagline': '滑动创意。发现人才。',
    'dashboard.desc': '管理您的设计，查看社区反馈，获取AI洞察。',
    'dashboard.totalDesigns': '设计总数',
    'dashboard.likesReceived': '获得的赞',
    'dashboard.designsSwiped': '已滑动设计',
    'dashboard.myDesigns': '我的设计',
    'dashboard.communityFeedback': '社区反馈',
    'dashboard.aiFeedback': 'AI反馈',
    'dashboard.noDesigns': '暂无设计',
    'dashboard.uploadFirst': '上传您的第一个设计开始',
    'dashboard.noAiFeedback': '暂无AI反馈',
    'dashboard.requestAi': '请求对您的设计进行AI分析以获取洞察',
    
    // Upload
    'upload.title': '上传设计',
    'upload.shareWork': '分享您的作品',
    'upload.desc': '分享您的创意并获得社区反馈',
    'upload.designImage': '设计图片',
    'upload.clickUpload': '点击上传',
    'upload.maxSize': 'PNG、JPG或WebP（最大5MB）',
    'upload.titleLabel': '标题',
    'upload.titlePlaceholder': '给您的设计起一个吸引人的标题',
    'upload.categoryLabel': '类别',
    'upload.selectCategory': '选择类别',
    'upload.descLabel': '描述',
    'upload.descPlaceholder': '介绍一下您的设计...',
    'upload.submit': '上传设计',
    
    // Designers
    'designers.title': '寻找设计师',
    'designers.desc': '发现可供雇用和合作的优秀设计师',
    'designers.searchPlaceholder': '按姓名、技能或位置搜索...',
    'designers.availableForHire': '可雇用',
    'designers.mostFollowers': '粉丝最多',
    'designers.mostDesigns': '作品最多',
    'designers.noFound': '未找到设计师',
    'designers.adjustFilters': '尝试调整搜索或筛选条件',
    'designers.followers': '粉丝',
    'designers.designs': '设计',
    
    // Profile
    'profile.yourProfile': '您的资料',
    'profile.showCommunity': '向SwipeLab社区展示自己',
    'profile.photo': '头像',
    'profile.photoDesc': '点击相机上传新照片',
    'profile.displayName': '显示名称',
    'profile.bio': '简介',
    'profile.bioPlaceholder': '向社区介绍自己...',
    'profile.availableForHire': '可供雇用',
    'profile.availableDesc': '让他人知道您可以接受工作',
    'profile.location': '位置',
    'profile.hourlyRate': '时薪',
    'profile.skills': '技能',
    'profile.addSkill': '添加技能（如Figma、UI设计）',
    'profile.saveChanges': '保存更改',
    
    // Feed
    'feed.guestViewing': '您正在以访客身份浏览',
    'feed.guestSwipes': '剩余{count}次免费滑动。登录获取无限滑动！',
    'feed.limitReached': '您已达到滑动限制。登录以继续！',
    'feed.designsLeft': '还有{count}个设计可探索',
    'feed.youLikeDesigns': '您喜欢这些设计！',
    'feed.swipedLimit': '您已滑动{count}个设计。请登录或创建免费账户以继续。',
    'feed.unlimitedSwipes': '无限滑动并保存您的收藏！',
    'feed.maybeLater': '稍后再说',
    'feed.registerFree': '免费注册',
  },
  ja: {
    // Auth
    'auth.welcome': 'ようこそ',
    'auth.welcomeBack': 'おかえりなさい',
    'auth.signInContinue': 'サインインしてデザインの旅を続けましょう',
    'auth.createAccount': 'アカウントを作成',
    'auth.startFeedback': 'デザインへのフィードバックを始めましょう',
    'auth.email': 'メール',
    'auth.password': 'パスワード',
    'auth.confirmPassword': 'パスワード確認',
    'auth.name': '名前',
    'auth.signIn': 'サインイン',
    'auth.signUp': '登録',
    'auth.signUpFree': '無料登録',
    'auth.noAccount': 'アカウントをお持ちでないですか？',
    'auth.hasAccount': '既にアカウントをお持ちですか？',
    'auth.emailPlaceholder': 'hello@example.com',
    'auth.namePlaceholder': 'フルネーム',
    'auth.passwordPlaceholder': '••••••••',
    'auth.selectLanguage': '言語を選択',
    
    // Common
    'common.loading': '読み込み中...',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.delete': '削除',
    'common.edit': '編集',
    'common.create': '作成',
    'common.search': '検索',
    'common.filter': 'フィルター',
    'common.all': 'すべて',
    'common.back': '戻る',
    'common.next': '次へ',
    'common.submit': '送信',
    'common.viewAll': 'すべて表示',
    'common.explore': '探索',
    'common.getStarted': '始める',
    'common.optional': '任意',
    
    // Hero/Landing
    'hero.tagline': 'アイデアをスワイプ。才能を発見。',
    'hero.poweredBy': 'AI搭載。',
    'hero.description': '作品を共有し、質の高いフィードバックを得る最大のデザイナーコミュニティ。',
    'hero.explorePortfolio': '世界をリードするデザインポートフォリオを探索',
    'hero.exploreDesc': '数百万のデザイナーとエージェンシーがSwipeLabでポートフォリオを公開しています — 世界最高のデザインとクリエイティブプロフェッショナルのホームです。',
    'hero.shareWork': '作品を共有する準備はできましたか？',
    'hero.shareWorkDesc': '毎日リアルなフィードバックを得ている数千人のデザイナーに参加しましょう。',
    'hero.createFreeAccount': '無料アカウント作成',
    
    // Services
    'services.title': 'デザイナーサービス',
    'services.description': 'トップタレントのプロフェッショナルデザインサービスを見つける',
    'services.createNew': '新しいサービスを作成',
    'services.myServices': 'マイサービス',
    'services.basicPlan': 'ベーシック',
    'services.standardPlan': 'スタンダード',
    'services.premiumPlan': 'プレミアム',
    'services.days': '日',
    'services.revisions': '回の修正',
    'services.orderNow': '今すぐ注文',
    'services.noServices': 'まだサービスがありません',
    'services.addService': 'サービスを追加',
    'services.serviceTitle': 'サービスタイトル',
    'services.serviceDescription': 'サービス説明',
    'services.category': 'カテゴリー',
    'services.price': '価格',
    'services.deliveryTime': '納期',
    'services.faq': 'よくある質問',
    'services.portfolio': 'ポートフォリオ',
    'services.testimonials': 'お客様の声',
    'services.basicInfo': '基本情報',
    'services.createDesc': 'デザインサービスを作成してクライアントを獲得しましょう',
    'services.pricingPlans': '料金プラン',
    'services.addImage': '画像を追加',
    'services.question': '質問',
    'services.answer': '回答',
    
    // Categories
    'category.ui_ux_design': 'UI/UXデザイン',
    'category.graphic_design': 'グラフィックデザイン',
    'category.illustration': 'イラスト',
    'category.branding': 'ブランディング',
    'category.web_design': 'Webデザイン',
    'category.mobile_design': 'モバイルデザイン',
    'category.motion_graphics': 'モーショングラフィックス',
    'category.other': 'その他',
    
    // Navigation
    'nav.feed': 'フィード',
    'nav.explore': '探索',
    'nav.designers': 'デザイナー',
    'nav.services': 'サービス',
    'nav.upload': 'アップロード',
    'nav.dashboard': 'ダッシュボード',
    'nav.messages': 'メッセージ',
    'nav.bookmarks': 'ブックマーク',
    'nav.profile': 'プロフィール',
    'nav.editProfile': 'プロフィール編集',
    'nav.myProfile': 'マイプロフィール',
    'nav.savedDesigns': '保存したデザイン',
    'nav.logout': 'ログアウト',
    'nav.login': 'ログイン',
    'nav.aiAssistant': 'AIアシスタント',
    
    // Dashboard
    'dashboard.tagline': 'アイデアをスワイプ。才能を発見。',
    'dashboard.desc': 'デザインを管理し、コミュニティからのフィードバックを確認し、AIの洞察を得ましょう。',
    'dashboard.totalDesigns': 'デザイン総数',
    'dashboard.likesReceived': '獲得したいいね',
    'dashboard.designsSwiped': 'スワイプしたデザイン',
    'dashboard.myDesigns': 'マイデザイン',
    'dashboard.communityFeedback': 'コミュニティフィードバック',
    'dashboard.aiFeedback': 'AIフィードバック',
    'dashboard.noDesigns': 'まだデザインがありません',
    'dashboard.uploadFirst': '最初のデザインをアップロードして始めましょう',
    'dashboard.noAiFeedback': 'AIフィードバックがまだありません',
    'dashboard.requestAi': 'デザインのAI分析をリクエストして洞察を得ましょう',
    
    // Upload
    'upload.title': 'デザインをアップロード',
    'upload.shareWork': '作品を共有',
    'upload.desc': 'あなたの創造性を共有し、コミュニティからフィードバックを得ましょう',
    'upload.designImage': 'デザイン画像',
    'upload.clickUpload': 'クリックしてアップロード',
    'upload.maxSize': 'PNG、JPGまたはWebP（最大5MB）',
    'upload.titleLabel': 'タイトル',
    'upload.titlePlaceholder': 'デザインにキャッチーなタイトルをつけましょう',
    'upload.categoryLabel': 'カテゴリー',
    'upload.selectCategory': 'カテゴリーを選択',
    'upload.descLabel': '説明',
    'upload.descPlaceholder': 'デザインについて教えてください...',
    'upload.submit': 'デザインをアップロード',
    
    // Designers
    'designers.title': 'デザイナーを探す',
    'designers.desc': '雇用可能な才能あるデザイナーを発見しましょう',
    'designers.searchPlaceholder': '名前、スキル、場所で検索...',
    'designers.availableForHire': '雇用可能',
    'designers.mostFollowers': 'フォロワー順',
    'designers.mostDesigns': 'デザイン数順',
    'designers.noFound': 'デザイナーが見つかりません',
    'designers.adjustFilters': '検索やフィルターを調整してみてください',
    'designers.followers': 'フォロワー',
    'designers.designs': 'デザイン',
    
    // Profile
    'profile.yourProfile': 'あなたのプロフィール',
    'profile.showCommunity': 'SwipeLabコミュニティに自分をアピールしましょう',
    'profile.photo': 'プロフィール写真',
    'profile.photoDesc': 'カメラをクリックして新しい写真をアップロード',
    'profile.displayName': '表示名',
    'profile.bio': '自己紹介',
    'profile.bioPlaceholder': 'コミュニティに自分のことを紹介しましょう...',
    'profile.availableForHire': '雇用可能',
    'profile.availableDesc': '仕事を受け付けていることを他の人に知らせましょう',
    'profile.location': '場所',
    'profile.hourlyRate': '時給',
    'profile.skills': 'スキル',
    'profile.addSkill': 'スキルを追加（例：Figma、UIデザイン）',
    'profile.saveChanges': '変更を保存',
    
    // Feed
    'feed.guestViewing': 'ゲストとして閲覧中です',
    'feed.guestSwipes': '残り{count}回の無料スワイプ。ログインして無制限に！',
    'feed.limitReached': 'スワイプ制限に達しました。ログインして続けましょう！',
    'feed.designsLeft': '残り{count}件のデザインを探索できます',
    'feed.youLikeDesigns': 'これらのデザインがお気に入りですね！',
    'feed.swipedLimit': '{count}件のデザインをスワイプしました。続けるにはログインまたは無料アカウントを作成してください。',
    'feed.unlimitedSwipes': '無制限スワイプ＆お気に入りを保存！',
    'feed.maybeLater': '後で',
    'feed.registerFree': '無料登録',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('swipelab-language');
    return (saved as Language) || 'id';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('swipelab-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
